# Use Node v8 as the base image.
FROM node

# You need to add commands for the following sections!!!

# --> Add everything in the current directory to our image, in the 'app' folder.

# --> Install dependencies

# --> Expose our server port.

# --> Run our app.
